name: demo
on: [push]
[MASTER]
disable=
    C0114,
    C0116
jobs:
  check-version:
    runs-on: 
      ubuntu-latest
    steps:
      - run: python --version
  check-pylint:
    runs-on: 
      ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install flask
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
